"""create pokemon_records table

Revision ID: 4ee000f50b34
Revises:
Create Date: 2025-11-26 09:47:02.080081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ee000f50b34"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemon_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pokemon_records_id"), "pokemon_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pokemon_records_pokemon_name"),
        "pokemon_records",
        ["pokemon_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pokemon_records_pokemon_name"), table_name="pokemon_records")
    op.drop_index(op.f("ix_pokemon_records_id"), table_name="pokemon_records")
    op.drop_table("pokemon_records")
    # ### end Alembic commands ###
