"""Add pokemon stats field

Revision ID: 76f5de356b55
Revises: 3233068d2641
Create Date: 2025-11-30 16:05:34.850428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76f5de356b55"
down_revision: Union[str, Sequence[str], None] = "3233068d2641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pokemon_records", sa.Column("pokedex_id", sa.Integer(), nullable=False)
    )
    op.add_column("pokemon_records", sa.Column("base_hp", sa.Integer(), nullable=False))
    op.add_column(
        "pokemon_records", sa.Column("base_attack", sa.Integer(), nullable=False)
    )
    op.add_column(
        "pokemon_records", sa.Column("base_defense", sa.Integer(), nullable=False)
    )
    op.add_column(
        "pokemon_records",
        sa.Column("base_special_attack", sa.Integer(), nullable=False),
    )
    op.add_column(
        "pokemon_records",
        sa.Column("base_special_defense", sa.Integer(), nullable=False),
    )
    op.add_column(
        "pokemon_records", sa.Column("base_speed", sa.Integer(), nullable=False)
    )
    op.add_column(
        "pokemon_records", sa.Column("total_base_stats", sa.Integer(), nullable=False)
    )
    op.add_column(
        "pokemon_records", sa.Column("power_index", sa.Float(), nullable=False)
    )
    op.add_column(
        "pokemon_records", sa.Column("tier", sa.String(length=1), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon_records", "tier")
    op.drop_column("pokemon_records", "power_index")
    op.drop_column("pokemon_records", "total_base_stats")
    op.drop_column("pokemon_records", "base_speed")
    op.drop_column("pokemon_records", "base_special_defense")
    op.drop_column("pokemon_records", "base_special_attack")
    op.drop_column("pokemon_records", "base_defense")
    op.drop_column("pokemon_records", "base_attack")
    op.drop_column("pokemon_records", "base_hp")
    op.drop_column("pokemon_records", "pokedex_id")
    # ### end Alembic commands ###
